; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps =
	adafruit/Adafruit BME280 Library@^2.3.0
